server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/palakendra?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root   # your MySQL username
    password: root   # your MySQL password
  jpa:
    hibernate:
      ddl-auto: none   # let Flyway manage schema
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration/common, classpath:db/migration/{vendor}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: "change-this-to-a-256-bit-random-string-change-this-to-a-256-bit-random"
  expiration-minutes: 60
  refresh-expiration-days: 7