server:
  port: ${PORT:8080} # defaults to 8080 if PORT is not set

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update      # or update if you want Spring to manage schema
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration/common, classpath:db/migration/{vendor}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: 60
  refresh-expiration-days: 7

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs/api   # load your "api" group


